### ISSUE TITLE
add 'tidy-html5' to fink

### ISSUE THREAD

**Issue by vielmetti** [fink/fink#122]
Hi, I am not sure if this is the right place for this query.

The `tidy` package which is in fink is rather old, and the project has been revived and has come out with a new 5.0.0 release suitable for distribution with fink. It's currently also distributed via `brew` and Macports.

See https://github.com/htacg/tidy-html5 for the github project, and http://www.html-tidy.org/ for the web site, and https://github.com/htacg/tidy-html5/issues/272 for the specific issue to track this request.

**Comment by TheSin-** [comment]
as long as the old tidy is left around for php5-tidy I'm find with it.

but libtidy-0.99.0-shlibs is required fro php5.

https://packages.debian.org/stretch/php5-tidy

I can test with the newer version if the packages is made but I do like to keep my packages/depends inline with debian, allows my dev env to match my production that way.

**Comment by akhansen** [comment]
It's not really the right place, since our package distribution hasn't moved to github yet--we do have plans to do that.  
Issues here should only touch upon the fink package manager itself, and this does not.
You can open a package request at http://sourceforge.net/p/fink/package-requests/ -- the title says for new packages, but updates are also welcome there.
In addition, the listed maintainer for the current tidy package <daniel AT daniel-johnson DOT org> is active and you can contact him about an update.

**Comment by vielmetti** [comment]
Ticked opened at https://sourceforge.net/p/fink/package-requests/1044/

**Comment by akhansen** [comment]
Thanks, I'll close this one out.
