### ISSUE TITLE
Fink Mojave cannot update 

### ISSUE THREAD

**Issue by biest3000** [fink/fink#189]

**Comment by biest3000** [comment]
Hi,

Since the initial hiccup I am happily using
fink on my MACs Mojave MACOS 10.14.5.

However, I have noticed 10 packages that can
no longer be updated:

- cernlib(-dev)
- extulis-makemaker-pm5182
- gcc5 (-compiler, -shlibs)
- gcc6-shlibs
- gd3-shlibs
- patchy4-gfortran
- xfig

1) Some would need to temporarily uninstall
packages but would not be able to be re-install
them (extulis-makemaker-pm5182, xfig)

2) Some try to install gcc8 which fails after
hours of cranking

Maybe that could be useful info for you guys.

Cheers, Frank

**Comment by nieder** [comment]
Do you have actual error messages for those failures? Most of those packages have had changes to them very recently to enable building on 10.14. Nevertheless, 10.14.5 really messed things up because apple changed the Perl version that comes with the system and so some of the failures might be due to that.

Please post individual error reports here: https://github.com/fink/fink-distributions/issues
