### ISSUE TITLE
consider adding -headerpad_max_install_names to LDFLAGS by default

### ISSUE THREAD

**Issue by nieder** [fink/fink#247]
Since we often have to edit binaries with install_name_tool (especially when still in %b which can be a long path), we should think about adding `-Wl,-headerpad_max_install_names` system wide to LDFLAGS.

See fink/fink-distributions#937 where forgetting to use it came up.

Currently, ~31 packages already use it. And ~66 packages use `install_name_tool` so might run into space allocation problems.

If it's in LDFLAGS, do we need to set it as `-Wl,-headerpad_max_install_names` ? In other words, who is reading LDFLAGS, the compiler or the linker?
If a package has `NoSetLDFLAGS: true`, we should not remove `-headerpad_max_install_names` (similar to MAKEFLAGS and `-j#`)

Because adding padding to the binary header will lead to a change in the deb, adding it into dpkg1.16 might be the best idea since that'll introduce deb changes everywhere.

FWIW, both homebrew and macports do this already.

**Comment by dmacks** [comment]
I think the ```-Wl,``` escape is more correct here because different toolchains either pass it directly to the linker or via the compiler front-end. I think the cmake toolchain already explicitly includes it on Darwin. I agree it's a good solution. I assume our own gccXX packages are ok with it?

I also agree that dpkg1.16 is a good point to make this sort of .deb-changing change. I was concerned that not having a way to disable it would be a problem (not inhibited by ```NoSetLDFLAGS```), but it's just an env-var, so ```*Script``` shell can manually override if necessary.

**Comment by dmacks** [comment]
Thinking more about the resulting .deb change, I can't see how it would be a problem (i.e., forward- and backward binary-comparible), since install_name_tool should never be run on an installed file and the size isn't read and used by anything externally.

**Comment by nieder** [comment]
Using gcc12 links cleanly with the flag (not a gcc12 package but hacked to use gcc12 and flag)

> /bin/sh ../libtool --silent --tag=CC   --mode=link gcc-fsf-12  -O2 -D_USE_MMAP  -fomit-frame-pointer -Wall -Wpointer-arith -Wsign-compare -Wmissing-declarations -Wdeclaration-after-statement -Werror-implicit-function-declaration -Wstrict-aliasing -Warray-bounds -Wstrict-prototypes  -L/sw/lib -Wl,-headerpad_max_install_names -o zzip zzip.o ../zzip/libzzip.la
